"""Add unique vote constraint

Revision ID: 20cf5c4d9da3
Revises: 27d7fc5536b1
Create Date: 2026-07-11 09:33:17.559382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20cf5c4d9da3'
down_revision = '27d7fc5536b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_election_vote', ['user_id', 'election_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_election_vote', type_='unique')

    # ### end Alembic commands ###
